import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dedbe8",
        "primary-container": "#ff79b0",
        "on-secondary": "#f6f0ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#004c5e",
        "tertiary-container": "#7adcfc",
        "on-surface-variant": "#5c5a63",
        "primary-dim": "#922158",
        "on-primary-container": "#54002e",
        "secondary-fixed-dim": "#c7bbff",
        "on-primary-fixed": "#160008",
        "inverse-primary": "#ff79b0",
        "on-error-container": "#510017",
        "inverse-surface": "#0e0e14",
        "tertiary-fixed": "#7adcfc",
        "surface-variant": "#dedbe8",
        "outline-variant": "#aeacb5",
        "secondary-dim": "#513ab0",
        "secondary": "#5e47bd",
        "on-tertiary": "#e1f6ff",
        "surface-bright": "#f9f5ff",
        "primary": "#a22e64",
        "on-secondary-fixed-variant": "#523bb1",
        "background": "#f9f5ff",
        "tertiary-dim": "#00576b",
        "surface-container-high": "#e4e1ed",
        "surface-tint": "#a22e64",
        "secondary-container": "#d5cbff",
        "tertiary-fixed-dim": "#6cceed",
        "on-tertiary-fixed-variant": "#00566a",
        "surface": "#f9f5ff",
        "outline": "#78767e",
        "error-dim": "#a70138",
        "error": "#b41340",
        "on-background": "#2f2e35",
        "primary-fixed": "#ff79b0",
        "inverse-on-surface": "#9e9ca5",
        "on-secondary-fixed": "#351594",
        "surface-container-low": "#f3effa",
        "surface-container": "#eae6f2",
        "on-primary": "#ffeff2",
        "surface-dim": "#d6d2e0",
        "on-tertiary-fixed": "#003745",
        "error-container": "#f74b6d",
        "secondary-fixed": "#d5cbff",
        "on-surface": "#2f2e35",
        "primary-fixed-dim": "#ef6ca2",
        "on-error": "#ffefef",
        "on-primary-fixed-variant": "#650038",
        "on-secondary-container": "#4930a7",
        "tertiary": "#00647a"
      },
      fontFamily: {
        "headline": ["var(--font-plus-jakarta)", "sans-serif"],
        "body": ["var(--font-be-vietnam)", "sans-serif"],
        "label": ["var(--font-be-vietnam)", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
} satisfies Config;
